[workspace]
resolver = "3"
members = ["bindings/*", "drivers/*", "kernel"]

[profile.dev]
panic = "abort"
debug = true
strip = false

[profile.release]
panic = "abort"
opt-level = "z"
debug = false
overflow-checks = false
strip = true
