[package]
name = "menix"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.71.1"

[dependencies]
portal = { path = "../portal", default-features = false }
bitflags = "2.9.0"
cfg-if = "1.0.0"
limine = { version = "0.3.1", optional = true }
seq-macro = "0.3.5"
spin = "0.9.8"

[features]
default = ["boot_limine"]

boot_limine = ["dep:limine"]

[profile.dev]
panic = "abort"
debug = true

[profile.release]
panic = "abort"
opt-level = "z"
debug = false
overflow-checks = false
strip = true
