[package]
name = "menix"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[build-dependencies]
bindgen = "0.71.1"

[dependencies]
bitflags = "2.9.0"
cfg-if = "1.0.0"
limine = { version = "0.4.0", optional = true }
seq-macro = "0.3.6"
spin = "0.9.8"
bytemuck = { version = "1.22.0", features = ["derive"] }

[features]
default = ["boot_limine"]

boot_limine = ["dep:limine"]

[profile.dev]
panic = "abort"
debug = true

[profile.release]
panic = "abort"
opt-level = "z"
debug = false
overflow-checks = false
strip = true
