name: Cargo Format Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build_and_check:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy rust-src rustfmt
      - run: cargo fmt --check
